### ISSUE TITLE
Task not working on MacOS agent

### ISSUE THREAD

**Issue by kevinDespoulains** [contrix09/install-flutter-sdk#1]
Hi contrix09,

I tried your extension on a MacOS agent but it didn't work. Here is the error message in case it can help you :

![image](https://user-images.githubusercontent.com/46108869/62601825-9309cc00-b8f2-11e9-8457-8c72ad860e89.png)

Your extension is a good idea, hope you will fix it soon ;)

**Comment by contrix09** [comment]
@kevinDespoulains Fixed.
